---
- name: 'PERSONAL : copy config files to volume'
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  loop:
    - { src: files/backup/automations.yaml, dest: /var/lib/docker/volumes/volume_homeassistant/_data/ }
    - { src: files/backup/scripts.yaml, dest: /var/lib/docker/volumes/volume_homeassistant/_data/ }
    - { src: files/backup/lovelace, dest: /var/lib/docker/volumes/volume_homeassistant/_data/.storage/ }
    - { src: files/backup/input_boolean, dest: /var/lib/docker/volumes/volume_homeassistant/_data/.storage/ }
    - { src: files/backup/input_datetime, dest: /var/lib/docker/volumes/volume_homeassistant/_data/.storage/ }
    - { src: files/backup/input_number, dest: /var/lib/docker/volumes/volume_homeassistant/_data/.storage/ }
    - { src: files/backup/input_text, dest: /var/lib/docker/volumes/volume_homeassistant/_data/.storage/ }
  become: true

- name: 'PERSONAL : clone add-ons repos'
  ansible.builtin.git:
    repo: '{{ item.repo }}'
    dest: '{{ item.dest }}'
  loop:
    - { repo: https://github.com/basnijholt/adaptive-lighting.git, dest: /tmp/adaptive-lighting }
    - { repo: https://github.com/dummylabs/thewatchman.git, dest: /tmp/thewatchman }
  register: clone
#  become: true

- name: 'PERSONAL : copy add-ons to directory'
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: /var/lib/docker/volumes/volume_homeassistant/_data/custom_components/
    mode: '0644'
    remote_src: true
  loop:
    - { src: /tmp/adaptive-lighting/custom_components/adaptive_lighting }
    - { src: /tmp/thewatchman/custom_components/watchman }
  when: clone.changed
  become: true
